CREATE TABLE history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    brief TEXT NOT NULL,
    result_json JSON NOT NULL,
    is_liked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_history_user FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT ck_history_expiry CHECK (expires_at > created_at)
);

CREATE INDEX idx_history_user_created ON history (user_id, created_at DESC, id DESC);
CREATE INDEX idx_history_user_liked_created ON history (user_id, is_liked, created_at DESC, id DESC);
CREATE INDEX idx_history_expires_at ON history (expires_at);

CREATE TABLE archive (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    brief TEXT NOT NULL,
    result_json JSON NOT NULL,
    original_created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    archived_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_archive_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

-- Archive owns its snapshot. There is deliberately no FK to expiring history.
CREATE INDEX idx_archive_user_archived ON archive (user_id, archived_at DESC, id DESC);
